language: java

before_script:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib dev beluga .
  - git clone git://github.com/HaxeBeluga/BelugaDemo.git BelugaDemo
  - haxelib run beluga setup templateTest
  - cd templateTest

script:
  - haxe templateTest.hxml