language: java

before_script:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib dev beluga .
  - git pull https://github.com/HaxeBeluga/BelugaDemo testdir

script:
  - haxe testdir belugademo.hxml
