language: java

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib dev beluga .
  - haxelib run beluga setup templateTest
  - haxelib install session
  - haxelib install tink_macro

script:
  - haxe templateTest/templateTest.hxml
  - haxe test/BelugaTest.hxml

notifications:
  slack: beluga:TnSEYGr5VTjnqJkbFKMhJorQ
